services:
  db:
    image: mysql:8.0.27
    user: "${UID}:${GID}"
    container_name: "${CONTAINER_PREFIX}_db"
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  admin:
    build:
      context: ./admin
      args:
        UID: 1000
        GID: 1000
    container_name: "${CONTAINER_PREFIX}_admin"
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT}:80"
    volumes:
      - ./media/data:/var/www/app/storage/app/media
      - ./admin/app:/var/www/app
      - ./admin/config/nginx/default.conf:/etc/nginx/sites-available/default
      - ./admin/config/php.ini:/usr/local/etc/php/php.ini

    environment:
      APP_URL: ${APP_ADMIN_URL}
      APP_FRONT_URL: ${APP_FRONT_URL}
      APP_ENV: ${ENVIROMENT}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]

